name: Deploy Shakesearch backend

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u maxhorstmann --password-stdin
    - name: Build Docker image
      run: docker build . -t maxhorstmann/shakesearch
    - name: Push Docker image
      run: docker push maxhorstmann/shakesearch
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy to ACI
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
           az container create \
            --resource-group shakesearch \
            --name shakesearch \
            --image maxhorstmann/shakesearch \
            --dns-name-label shakesearch  \
            --ports 9200


